version: "3"
services:

  # ┏━ NextJS | Frontend, react based compiled webapp.
  app:
    image: node:lts-alpine
    restart: unless-stopped
    command: ["yarn", "deploy"]
    ports: [$APP_PORT:3000]
    depends_on: [database]
    working_dir: /usr/app
    volumes: [.:/usr/app]
    profiles: ["prod"]
    env_file: .env

  # ┏━ Postgres | Database, SQL based data storage.
  database:
    image: postgis/postgis:latest
    restart: unless-stopped
    ports: [$DATABASE_PORT:5432]
    volumes: [./data:/var/lib/postgresql/data]
    environment: 
      POSTGRES_PASSWORD: $DATABASE_PASS
